# =============================================================================
#  ~/.zshrc  —  managed by iterm-dotfiles
#
#  Design:
#    * Everything OUTSIDE the iTerm2 block loads in BOTH macOS Terminal.app
#      and iTerm2. This keeps the stock terminal clean and fast.
#    * The oh-my-zsh framework, powerlevel10k theme, and plugins load ONLY
#      inside iTerm2 (detected via $TERM_PROGRAM == "iTerm.app").
#    * Language tooling (pyenv, coursier/scala) lives in the shared region so
#      it works everywhere.
#    * Machine-specific bits (extra PATHs, secrets) go in ~/.zshrc.local, which
#      is git-ignored. See zsh/.zshrc.local.example.
# =============================================================================

# ── powerlevel10k instant prompt — all terminals except Terminal.app ─────────
# Gating on != Apple_Terminal (not == iTerm.app) means the full stack also
# loads inside tmux panes and Linux terminals without any extra config.
if [[ "$TERM_PROGRAM" != "Apple_Terminal" ]]; then
  if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
  fi
fi

# =============================================================================
#  SHARED CONFIG  —  loads in BOTH Terminal.app and iTerm2
# =============================================================================

# --- History ---
HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000
setopt SHARE_HISTORY HIST_IGNORE_ALL_DUPS HIST_IGNORE_SPACE INC_APPEND_HISTORY

# --- Sensible defaults ---
setopt AUTO_CD                # `foo` cds into ./foo
setopt INTERACTIVE_COMMENTS   # allow # comments in interactive shells

# --- Your own aliases / exports / functions ---
# Paste anything from your original ~/.zshrc here (or drop it in ~/.zshrc.local).
# Examples:
# alias ll='ls -lah'
# alias gs='git status'
# export EDITOR='vim'

# --- Python (pyenv) — both terminals ---
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
command -v pyenv >/dev/null 2>&1 && eval "$(pyenv init -)"

# --- Scala / JVM (coursier) — both terminals ---
# `cs setup` writes PATH entries to ~/.zprofile, so scala/sbt/scalafmt are
# already on PATH in every login shell. Nothing extra needed here.

# --- Machine-local overrides (git-ignored) ---
[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"

# =============================================================================
#  OH-MY-ZSH  —  all terminals except macOS Terminal.app
# =============================================================================
if [[ "$TERM_PROGRAM" != "Apple_Terminal" ]]; then
  export ZSH="$HOME/.oh-my-zsh"
  ZSH_THEME="powerlevel10k/powerlevel10k"

  plugins=(
    git
    python pip virtualenv pyenv
    scala sbt
    zsh-autosuggestions
    zsh-syntax-highlighting   # keep this LAST
  )

  source "$ZSH/oh-my-zsh.sh"

  # p10k prompt config (generated by `p10k configure`)
  [[ -f "$HOME/.p10k.zsh" ]] && source "$HOME/.p10k.zsh"

  # Re-declare here anything oh-my-zsh overrode that you want to win in iTerm2.
fi
